// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: observerAcl.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObserverAclRow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number      string `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Time        string `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	TxId        string `protobuf:"bytes,3,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Address     string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	AccountInfo string `protobuf:"bytes,5,opt,name=account_info,json=accountInfo,proto3" json:"account_info,omitempty"`
	Pk          string `protobuf:"bytes,6,opt,name=pk,proto3" json:"pk,omitempty"`
}

func (x *ObserverAclRow) Reset() {
	*x = ObserverAclRow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_observerAcl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObserverAclRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserverAclRow) ProtoMessage() {}

func (x *ObserverAclRow) ProtoReflect() protoreflect.Message {
	mi := &file_observerAcl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserverAclRow.ProtoReflect.Descriptor instead.
func (*ObserverAclRow) Descriptor() ([]byte, []int) {
	return file_observerAcl_proto_rawDescGZIP(), []int{0}
}

func (x *ObserverAclRow) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *ObserverAclRow) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *ObserverAclRow) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *ObserverAclRow) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ObserverAclRow) GetAccountInfo() string {
	if x != nil {
		return x.AccountInfo
	}
	return ""
}

func (x *ObserverAclRow) GetPk() string {
	if x != nil {
		return x.Pk
	}
	return ""
}

type ObserverAclData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rows []*ObserverAclRow `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
}

func (x *ObserverAclData) Reset() {
	*x = ObserverAclData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_observerAcl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObserverAclData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserverAclData) ProtoMessage() {}

func (x *ObserverAclData) ProtoReflect() protoreflect.Message {
	mi := &file_observerAcl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserverAclData.ProtoReflect.Descriptor instead.
func (*ObserverAclData) Descriptor() ([]byte, []int) {
	return file_observerAcl_proto_rawDescGZIP(), []int{1}
}

func (x *ObserverAclData) GetRows() []*ObserverAclRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

var File_observerAcl_proto protoreflect.FileDescriptor

var file_observerAcl_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x63, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9e, 0x01, 0x0a, 0x0e, 0x4f,
	0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x63, 0x6c, 0x52, 0x6f, 0x77, 0x12, 0x16, 0x0a,
	0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x74, 0x78, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x78, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x70,
	0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x70, 0x6b, 0x22, 0x3c, 0x0a, 0x0f, 0x4f,
	0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x63, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x29,
	0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x63, 0x6c,
	0x52, 0x6f, 0x77, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_observerAcl_proto_rawDescOnce sync.Once
	file_observerAcl_proto_rawDescData = file_observerAcl_proto_rawDesc
)

func file_observerAcl_proto_rawDescGZIP() []byte {
	file_observerAcl_proto_rawDescOnce.Do(func() {
		file_observerAcl_proto_rawDescData = protoimpl.X.CompressGZIP(file_observerAcl_proto_rawDescData)
	})
	return file_observerAcl_proto_rawDescData
}

var file_observerAcl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_observerAcl_proto_goTypes = []interface{}{
	(*ObserverAclRow)(nil),  // 0: proto.ObserverAclRow
	(*ObserverAclData)(nil), // 1: proto.ObserverAclData
}
var file_observerAcl_proto_depIdxs = []int32{
	0, // 0: proto.ObserverAclData.rows:type_name -> proto.ObserverAclRow
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_observerAcl_proto_init() }
func file_observerAcl_proto_init() {
	if File_observerAcl_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_observerAcl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObserverAclRow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_observerAcl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObserverAclData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_observerAcl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_observerAcl_proto_goTypes,
		DependencyIndexes: file_observerAcl_proto_depIdxs,
		MessageInfos:      file_observerAcl_proto_msgTypes,
	}.Build()
	File_observerAcl_proto = out.File
	file_observerAcl_proto_rawDesc = nil
	file_observerAcl_proto_goTypes = nil
	file_observerAcl_proto_depIdxs = nil
}
